// Generates src/index.js — the public entry point that re-exports every
// component. Run via `npm run gen:barrel`. Safe to re-run whenever a
// component is added; all exports are unique (no name collisions).
import { readdirSync, writeFileSync, statSync } from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const componentsDir = path.join(root, "src", "components");

const categories = readdirSync(componentsDir).filter((c) =>
  statSync(path.join(componentsDir, c)).isDirectory(),
);

const lines = [
  "// AUTO-GENERATED by scripts/generate-barrel.mjs — do not edit by hand.",
  "// Public entry for the Agentaily design system component library.",
  "// Consumers must also import the tokens once: `import \"@agentaily/design-system/styles.css\"`.",
  "",
];

let count = 0;
for (const cat of categories.sort()) {
  const dir = path.join(componentsDir, cat);
  const files = readdirSync(dir)
    .filter((f) => f.endsWith(".jsx") && !f.endsWith(".stories.jsx"))
    .sort();
  if (!files.length) continue;
  lines.push(`// ${cat}`);
  for (const f of files) {
    lines.push(`export * from "./components/${cat}/${f}";`);
    count++;
  }
  lines.push("");
}

writeFileSync(path.join(root, "src", "index.js"), lines.join("\n"));
console.log(`Wrote src/index.js — ${count} component modules across ${categories.length} categories.`);
